server:
  port: 8080
  servlet:
    context-path: /framework/oauth/authorization/api

spring:
  security:
    user:
      password: ${random.uuid}
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: always
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin.sprouts.kr/
  cloud:
    discovery:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:sprouts_framework_oauth_authorization
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            store_data_at_delete: true
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        legacy_limit_handler: true
        jdbc:
          time_zone: Asia/Seoul

eureka:
  instance:
     instance-id: ${random.uuid}
     prefer-ip-address: true
     lease-renewal-interval-in-seconds: 3
     lease-expiration-duration-in-seconds: 10
  client:
    client:
      enabled: false
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    disable-delta: false
    service-url:
      defaultZone: http://discovery.framework.sprouts.kr/eureka/

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enable: true
    refresh:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
    gateway:
      enabled: true
  info:
    java:
      enabled: true

logbook:
  include:
    - ${server.servlet.context-path}/**
  exclude:
    - ${server.servlet.context-path}/actuator/**
    - ${server.servlet.context-path}/h2-console/**
  filter.enabled: true
  secure-filter.enabled: true
  format.style: json
  strategy: default
  minimum-status: 400
  obfuscate:
    headers:
      - Authorization
    parameters:
      - access_token
  write:
    chunk-size: 4000

logging.level:
  root: WARN
  org.zalando.logbook: TRACE
  kr.sprouts: DEBUG


sprouts:
  application:
    local:
      authorize:
        accessToken:
          providerId: 00000083-3bae-4b13-b033-ebd8e779a1b0
          validityInMinutes: 30
        refreshToken:
          providerId: eeeeee4b-38b8-4ed1-b7ac-ae959aab7d23
          validityInMinutes: 120
    remote:
      resource:
        host: http://gateway.framework.sprouts.kr
        contextPath: /framework/oauth/resource/api
        authorization:
          header: Authorization
          prefix: Bearer
          value: rO0ABXNyADtrci5zcHJvdXRzLmZyYW1ld29yay5saWJyYXJ5LnNlY3VyaXR5LmNyZWRlbnRpYWwuQ3JlZGVudGlhbJOquvmv76gkAgADTAALY29uc3VtZXJJZHN0ABBMamF2YS91dGlsL0xpc3Q7TAAKcHJvdmlkZXJJZHQAEExqYXZhL3V0aWwvVVVJRDtMAAV2YWx1ZXQAEkxqYXZhL2xhbmcvU3RyaW5nO3hwc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNpemV4cAAAAAF3BAAAAAFzcgAOamF2YS51dGlsLlVVSUS8mQP3mG2FLwIAAkoADGxlYXN0U2lnQml0c0oAC21vc3RTaWdCaXRzeHChTQ_kWBO3xf___zhQUkM6eHNxAH4AB7OGiudIsOOU____MkhYQ8h0AQBhUXhxR0FmRTdmN203bGtxVmRTejd6VzlmNDQwS1RXM2hxSDJhRmxRemRkb2xkVDUzSHZvRm1jYXBNb0ZGN0FmbGZ0amV1Mk9uZ0dzcFc2TGl6YzFVZ1hBbXRsQ0ZrLUNHTktHTTBRUWZlNWd3V0Y5YlVrSXVTOW1lMXpLVFBrMUtTc2JCOEdQcGRhMThFWVBCRHNZTDhkSGJncmR6VUhhakFnS1liNG1VWnhTYWhWOXFJV3dRVnB1ZXRRQVhMS3pleEdqcGRibDFndEJ2MXYtbHpKSjU2M1JpTzhES2NzMzk0cmc1TjN2V2dLNThhOUl1UFdVTVFtcFBhTFVZX3p5
  logstash-appender:
    name: LOGSTASH
    identifier: ${spring.application.name}-${spring.profiles.active}
    destinations:
      - host: 127.0.0.1
        port: 5045
  web:
    response:
      default-host: gateway
      hosts:
        - name: gateway
          url: http://127.0.0.1:8080${server.servlet.context-path}
  security:
    http:
      permit-all.patterns:
        - /actuator/**
        - /h2-console/**
      permit-post.patterns:
        - /authorize
        - /authorize/refresh
    credential:
      header:
        name: Authorization
        prefix: Bearer
        codec: BASE64_URL
      providers:
        - id: 00000083-3bae-4b13-b033-ebd8e779a1b0
          name: AccessTokenProvider
          type: BEARER_TOKEN
          algorithm: HS512
          codec: BASE64_URL
          encodedSecret: gj9OkDY_BRelaDXsOg2bDOz4EJR7SXvcFCFspCTb4GKdGx7PxVqWidIrY_YtBJsEcndGROc-RUww2twUwTR6Lg==
          targetConsumers:
            - id: 000000fc-1934-42af-90f5-3004cd40257e
              name: AccessTokenConsumer
        - id: eeeeee4b-38b8-4ed1-b7ac-ae959aab7d23
          name: RefreshTokenProvider
          type: BEARER_TOKEN
          algorithm: HS512
          codec: BASE64_URL
          encodedSecret: 71WjYzk1oKyLKOuDDrINcTXnX5sVKwZgzFslmv3z9jQlFsSHgITpRIglkZr7hRRk_XmZ1Sb0FGLPnk6197Kxtw==
          targetConsumers:
            - id: eeeeee16-6c3c-4aa6-935b-7b6fcd648938
              name: RefreshTokenConsumer
        - id: ffffff32-4858-43c8-b386-8ae748b0e394
          name: ApiKeyProvider
          type: API_KEY
          algorithm: AES256
          codec: BASE64_URL
          encodedSecret: VhIW0Qwfqwm9KGVk6dBfyD0iBlfJSOzCofPdoxUqABg=
          targetConsumers:
            - id: ffffff38-5052-433a-a14d-0fe45813b7c5
              name: ApiKeyConsumer
      consumers:
        - id: 000000fc-1934-42af-90f5-3004cd40257e
          name: AccessTokenConsumer
          type: BEARER_TOKEN
          algorithm: HS512
          codec: BASE64_URL
          encodedSecret: gj9OkDY_BRelaDXsOg2bDOz4EJR7SXvcFCFspCTb4GKdGx7PxVqWidIrY_YtBJsEcndGROc-RUww2twUwTR6Lg==
          validProviders:
            - id: 00000083-3bae-4b13-b033-ebd8e779a1b0
              name: AccessTokenProvider
        - id: eeeeee16-6c3c-4aa6-935b-7b6fcd648938
          name: RefreshTokenConsumer
          type: BEARER_TOKEN
          algorithm: HS512
          codec: BASE64_URL
          encodedSecret: 71WjYzk1oKyLKOuDDrINcTXnX5sVKwZgzFslmv3z9jQlFsSHgITpRIglkZr7hRRk_XmZ1Sb0FGLPnk6197Kxtw==
          validProviders:
            - id: eeeeee4b-38b8-4ed1-b7ac-ae959aab7d23
              name: RefreshTokenProvider
        - id: ffffff38-5052-433a-a14d-0fe45813b7c5
          name: ApiKeyConsumer
          type: API_KEY
          algorithm: AES256
          codec: BASE64_URL
          encodedSecret: VhIW0Qwfqwm9KGVk6dBfyD0iBlfJSOzCofPdoxUqABg=
          validProviders:
            - id: ffffff32-4858-43c8-b386-8ae748b0e394
              name: ApiKeyProvider
